//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analysis_of_urban_passenger_transport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int id { get; set; }
        public string id_tip { get; set; }
        public string RouteNumber { get; set; }
        public string TypeOfFlight { get; set; }
        public string EndA { get; set; }
        public string EndB { get; set; }
        public string EndC { get; set; }
        public string SwitchingToRoutes { get; set; }
        public string FeaturesOfRoute { get; set; }
        public string MachineName { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public string Printing { get; set; }
    
        public virtual tip_trans tip_trans { get; set; }
    }
}
